#!/bin/bash
exec &> >(tee -a kubeadm_run.log)

# Source env vars
source ARMadillo/deploy/multi_master/env_vars.sh

# Move certs generated by kubeadm which was copied from master01
sudo mkdir -p /etc/kubernetes/pki/etcd
sudo mv /home/${Pi_USERNAME}/ca.crt /etc/kubernetes/pki/
sudo mv /home/${Pi_USERNAME}/ca.key /etc/kubernetes/pki/
sudo mv /home/${Pi_USERNAME}/sa.pub /etc/kubernetes/pki/
sudo mv /home/${Pi_USERNAME}/sa.key /etc/kubernetes/pki/
sudo mv /home/${Pi_USERNAME}/front-proxy-ca.crt /etc/kubernetes/pki/
sudo mv /home/${Pi_USERNAME}/front-proxy-ca.key /etc/kubernetes/pki/
sudo mv /home/${Pi_USERNAME}/etcd-ca.crt /etc/kubernetes/pki/etcd/ca.crt
sudo mv /home/${Pi_USERNAME}/etcd-ca.key /etc/kubernetes/pki/etcd/ca.key
sudo mv /home/${Pi_USERNAME}/admin.conf /etc/kubernetes/admin.conf

# Joining the master to the cluster using the token generated from the kubeadm init on master01
echo "Wait, pulling k8s images needed..."
sudo kubeadm config images pull
sudo ./join_master.sh

mkdir -p $HOME/.kube
sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config

# Getting status
echo "Almost there, wait a bit for the master node to be in 'Ready' state (sleeping 90s)"
sleep 90

kubectl get nodes

# Cleanup
mkdir -p ARMadillo/artifacts
sudo mv join_master.sh ARMadillo/artifacts
sudo mv config ARMadillo/artifacts
sudo mv ca.pem ARMadillo/artifacts
sudo rm -f admin.conf 